extern "C" __global__ void gpu_cabt_state_fields_probe(gc_u64* output) {
    if (blockIdx.x != 0 || threadIdx.x != 0) return;
    gc_i32 c = 0;

    gpu_cabt::CardNextTurnFields next{};
    next.fields.cannot_use_attack_id = 0x1234;
    next.fields.cannot_use_attack_id2 = 0x2345;
    next.fields.damage_change = -333;
    next.fields.damage_change_active = 444;
    next.fields.damage_change_my_attack = -555;
    next.fields.attack_cost_change = -7;
    next.fields.retreat_cost_change = 9;
    next.fields.cannot_retreat = true;
    next.fields.cannot_hand_attach_energy = false;
    next.fields.cannot_attack = true;
    next.fields.cannot_attack_less_equal_energy2 = true;
    next.fields.attack_coin = false;
    next.fields.attack_coin2 = true;
    for (gc_i32 i = 0; i < 4; ++i) output[c++] = next.value[i];

    gpu_cabt::CardNextMyTurnEnemyFields enemy{};
    enemy.fields.take_damage_change = -771;
    output[c++] = enemy.value[0];

    gpu_cabt::CardTurnFields turn{};
    turn.fields.damage_change_this_turn = -101;
    turn.fields.damage_change_ex_this_turn = 202;
    turn.fields.ko_cause_ref = 77;
    turn.fields.ko_prize_change_always = -3;
    turn.fields.ko_prize_change = 4;
    turn.fields.appear = true;
    turn.fields.evolved = false;
    turn.fields.bench_to_active = true;
    turn.fields.ko = true;
    turn.fields.ko_attack_damage = false;
    turn.fields.ko_enemy_attack_damage = true;
    turn.fields.ko_enemy_attack_damage_active = false;
    turn.fields.ko_enemy_ex_attack_damage = true;
    turn.fields.ko_enemy_terastal_attack_damage = true;
    turn.fields.ko_enemy_n_attack_damage = false;
    turn.fields.ko_full = true;
    turn.fields.ko_prize_plus1 = false;
    turn.fields.ko_prize_decrease_once = true;
    turn.fields.ko_prize_zero = true;
    turn.fields.ko_no_damage_and_effect_attack_next_enemy_turn = true;
    for (gc_i32 i = 0; i < 3; ++i) output[c++] = turn.value[i];

    gpu_cabt::CardContinualFields continual{};
    continual.fields.hp_change = 11;
    continual.fields.damage_change = -12;
    continual.fields.damage_change_active = 13;
    continual.fields.damage_change_ex = -14;
    continual.fields.damage_change_ability = 15;
    continual.fields.damage_change_evolved = -16;
    continual.fields.damage_change_enemy_taken_prize = 17;
    continual.fields.take_damage_change = -18;
    continual.fields.take_enemy_attack_damage_change = 19;
    continual.fields.take_enemy_ability_pokemon_attack_damage_change = -20;
    continual.fields.take_enemy_fire_or_water_pokemon_attack_damage_change = 21;
    continual.fields.take_enemy4_type_pokemon_attack_damage_change = -22;
    continual.fields.no_damage_greater_equal = 230;
    continual.fields.retreat_cost_change = -4;
    continual.fields.attack_cost_change_colorless = 5;
    continual.fields.attack_cost_down = -6;
    continual.fields.attack_cost_down_colorless_own_attack = 7;
    continual.fields.type_index = 8;
    continual.fields.weakness_index = 9;
    continual.fields.no_ability = true;
    continual.fields.no_ko_me_ability = false;
    continual.fields.no_damage_enemy_ability_pokemon_attack = true;
    continual.fields.no_damage_enemy_ex_attack = false;
    continual.fields.no_damage_enemy_basic_ex_attack = true;
    continual.fields.no_damage_and_effect_enemy_terastal_attack = false;
    continual.fields.no_damage_and_effect_enemy_special_energy_attack = true;
    continual.fields.no_damage_enemy_attack = true;
    continual.fields.no_effect_enemy_attack = false;
    continual.fields.no_effect_enemy_item = true;
    continual.fields.no_effect_enemy_supporter = false;
    continual.fields.no_damage_counter_enemy_attack_ability = true;
    continual.fields.no_enemy_ability = true;
    continual.fields.no_special_condition = false;
    continual.fields.no_sleep_paralyze_confuse = true;
    continual.fields.no_sleep = false;
    continual.fields.no_retreat_cost = true;
    continual.fields.no_prize_ex = false;
    continual.fields.not_recover_confuse_evolve = true;
    continual.fields.can_use_pre_evolution_attack = true;
    continual.fields.can_evolve_appear_turn = false;
    continual.fields.can_evolve_grass_appear_turn = true;
    continual.fields.can_attack_first = false;
    continual.fields.cannot_retreat = true;
    continual.fields.cannot_attack = true;
    continual.fields.cannot_to_hand = false;
    continual.fields.cannot_move_damage_counter = true;
    continual.fields.attack_energy_colorless_one = false;
    continual.fields.attack_energy_psychic_one = true;
    continual.fields.double_grass_energy = true;
    continual.fields.no_damage_coin = false;
    continual.fields.ko_by_damage_to_hand = true;
    continual.fields.basic_prize_plus1 = false;
    continual.fields.double_attack = true;
    continual.fields.tool2 = false;
    continual.fields.tool4 = true;
    continual.fields.technical_machine = true;
    continual.fields.special_flag_tool = false;
    continual.fields.rainbow_dna = true;
    continual.fields.can_play = true;
    for (gc_i32 i = 0; i < 5; ++i) output[c++] = continual.value[i];

    gpu_cabt::PlayerNextTurnFields pn{};
    pn.fields.metal_damage_change = -321;
    pn.fields.cannot_attack_less_equal_energy2 = true;
    pn.fields.cannot_play_item = false;
    pn.fields.cannot_play_supporter = true;
    pn.fields.cannot_play_stadium = true;
    pn.fields.cannot_play_special_energy = false;
    pn.fields.cannot_evolve = true;
    pn.fields.cannot_retreat_poison = false;
    output[c++] = pn.value;

    gpu_cabt::PlayerActiveFields pa{};
    pa.fields.poison_damage_counter = 12;
    pa.fields.bad_status = 3;
    pa.fields.burned = true;
    output[c++] = pa.value;

    gpu_cabt::PlayerContinualFields pc{};
    pc.fields.poison_damage_change = -111;
    pc.fields.burn_damage_change = 222;
    pc.fields.poison_damage_change_not_darkness = -7;
    pc.fields.bench_capacity = 8;
    pc.fields.cannot_play_item = true;
    pc.fields.cannot_play_stadium = false;
    pc.fields.cannot_play_tool = true;
    pc.fields.cannot_play_ace_spec = true;
    pc.fields.cannot_play_ability_pokemon_not_rocket = false;
    pc.fields.cannot_trash_to_hand_ability_or_trainers = true;
    output[c++] = pc.value;

    gpu_cabt::PlayerTurnFields pt{};
    pt.fields.player_damage_change = -100;
    pt.fields.player_damage_change_ex = 200;
    pt.fields.player_damage_change_my_fighting = -300;
    pt.fields.take_prize_count_change_terastal_attack_ko_active = 5;
    pt.fields.take_prize_count_change_n_attack_ko_active = -6;
    output[c++] = pt.value;

    gpu_cabt::StateTurnFields st{};
    st.fields.supporter_played = true;
    st.fields.stadium_played = false;
    st.fields.energy_played = true;
    st.fields.retreated = true;
    st.fields.turn_end = false;
    output[c++] = st.value;

    gpu_cabt::StateContinualFields sc{};
    sc.fields.no_tool_effect = true;
    output[c++] = sc.value;
}
